// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"database/sql"
	"time"
)

type AccountMgtAccount struct {
	ID        int64         `json:"id"`
	OwnerID   int64         `json:"owner_id"`
	Balance   sql.NullInt64 `json:"balance"`
	AccountNo string        `json:"account_no"`
	Currency  string        `json:"currency"`
	CreatedAt time.Time     `json:"created_at"`
}

type AccountMgtEntry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// Can either be negative or positive
	Amount    sql.NullInt64 `json:"amount"`
	CreatedAt time.Time     `json:"created_at"`
}

type AccountMgtTransfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// Must be positive
	Amount    sql.NullInt64 `json:"amount"`
	CreatedAt time.Time     `json:"created_at"`
}

type UserMgtUser struct {
	ID        int64          `json:"id"`
	FullName  string         `json:"full_name"`
	IDCardNo  sql.NullString `json:"id_card_no"`
	CreatedAt time.Time      `json:"created_at"`
}
