// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO user_mgt.users (
  full_name, 
  id_card_no
) VALUES (
  $1, $2
)
RETURNING id, full_name, id_card_no, created_at
`

type CreateUserParams struct {
	FullName string         `json:"full_name"`
	IDCardNo sql.NullString `json:"id_card_no"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (UserMgtUser, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.FullName, arg.IDCardNo)
	var i UserMgtUser
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.IDCardNo,
		&i.CreatedAt,
	)
	return i, err
}
